게시글, 댓글, 대댓글 작성 시간 수정
Stop-smoke/KekKek pull request #205
Opened 2024-07-20 16:40 UTC by dongwonyang

화면상으로 문제 없이 했지만 데이터를 저장하는 과정에서 무슨 문제가 생긴 게 확실합니다.

.toFireBaseTimeStamp().toLocalDateTitem()으로 형변환을 두번 할 시 게시글은 시간이 다르게 저장되고 댓글, 대댓글은 시간이 현재 시간으로 저장되더군요..

임시방편으로 일단 비교시간인 LocalDateTime에도 두번의 형변환하고 댓글, 대댓글의 경우 가져온 데이터의 시간에도 두번의 형변환을 통해서 이를 화면상으로는 제대로 출력하도록 바꾸었습니다만..

 왜 이런 문제가 생겼는지는 찾아보고 있지만 아직까지는 잘 모르겠어서 해결방법은 더 찾아보겠습니다.

2024-07-21 09:52 UTC, xeejin approved these changes

2024-07-22 02:03 UTC, agvber requested changes
도메인 레이어 Mapper가 프레젠테이션 Utils로 넘어 갔습니다
(엄연히 말해서 도메인 Mapper 보단 data Mapper도 섞여 있네요)

서버 시간 버그는 확인해보겠습니다

2024-07-23 12:44 UTC, agvber commented on app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListItem.kt
> +        postType = category.toStringKR() ?: "",
이부분 StringKR로 나누지 마시고 String.xml 파일에서 resource ID로 Mapping 해주세요

2024-07-23 12:46 UTC, agvber commented on app/src/main/java/com/stopsmoke/kekkek/presentation/mapper/PostCategortMapper.kt
> +fun PostCategory.toStringKR(): String? = when (this) {
이 함수는 위에 함수와 겹치는 것 같은데 없어도 되지 않을까요?

2024-07-23 12:47 UTC, agvber commented on app/src/main/java/com/stopsmoke/kekkek/presentation/post/edit/PostEditFragment.kt
> +        uiState.collectLatestWithLifecycle(lifecycle) {
uiState 보단 postEditUiState 변수명이 상세해서 좋을 것 같습니다

2024-07-23 12:50 UTC, agvber commented on app/src/main/java/com/stopsmoke/kekkek/core/data/mapper/CommentMapper.kt
> +import com.stopsmoke.kekkek.presentation.mapper.toPostCategory
Data -> Presentation 직접 의존합니다
이부분 수정 부탁드립니다

2024-07-24 17:43 UTC, dongwonyang commented on app/src/main/java/com/stopsmoke/kekkek/presentation/mapper/PostCategortMapper.kt
> +fun PostCategory.toStringKR(): String? = when (this) {
이거에 대해서는 context를 사용해 getString으로 가져오는데 fragment 내부가 아니어서 context를 가져올 수 없는 경우 getString함수를 어떻게 가져와야 하나 보다가 application딴에서 ApplcationContext를 가져와서 사용해도 되나 고민하다 두었습니다. 이게 applicationContext를 사용해도 되나요?

2024-07-24 18:06 UTC, dongwonyang commented on app/src/main/java/com/stopsmoke/kekkek/presentation/post/edit/PostEditFragment.kt
> +        uiState.collectLatestWithLifecycle(lifecycle) {
PostEditViewModel에 속해있어서 각 viewModel이 sharedViewModel이어서 uiState가 여러개 필요하지 않은 이상 헷갈리지 않을 거 같아서 uiState로 했었습니다. viewModel에 있는 uiState명들 고쳐놓을게요.

2024-07-25 00:13 UTC, agvber commented on app/src/main/java/com/stopsmoke/kekkek/presentation/mapper/PostCategortMapper.kt
> +fun PostCategory.toStringKR(): String? = when (this) {
근데 코드 상으로 보았을 경우에 context 없는 부분에서 굳이 저 코드를 사용할 이유가 없어 보이는데요?
어디 부분이 그런지 알 수 있을까요??

2024-07-25 11:08 UTC, agvber approved these changes

2024-07-25 11:09 UTC, merged